### PR TITLE
Feat #4

### PR DESCRIPTION
**Pull request by Wansmer**

### CODE REVIEW

**Comment by Wansmer** [comment]
From #4 

> just calling `vim.lsp.buf.format` might be a bit problematic, because it's argument such as timeout and filter would need to be configurable

I checked it again. 
`filter` like argument in `vim.lsp.buf.format` has no effect when lsp-client hasn't formatter (just notifying what 'no lsp attached').
`timeout_ms` 1000 ms by default and it enough, I think.

I added a wrapper with filtering lsp-clients. 
If no one client has no formatter for that buffer,  `vim.lsp.buf.format` just no call. When formatter is present, the action will be the same if the user called it himself.

**Comment by LostInTheLogs** [comment]
The problem is that if you have multiple LSPs attached then it will ask which one to use for formatting, I think it's easier to  leave creating this function up to the user

I might create a function that allows to range format with formatters that don't support it, then I'll be able to better integrate this plugin into null-ls and it will be one of the sources

**Comment by Wansmer** [comment]
> The problem is that if you have multiple LSPs attached then it will ask which one to use for formatting, I think it's easier to leave creating this function up to the user

Yes, I understand reason.
Just in recent time prompt with ask no shown more (at least at me with nvim 0.8). And I tested with two formatters for buffer (null-ls with tidy and html-lsp) - by default calling last at order without asking.
Need this feature or not – on your view.
Maybe make sense add note to README, how to format entire buffer by one keymap, until you don't add it in sources null-ls.

**Comment by LostInTheLogs** [comment]
refactor is now merged into main

**Pull request closed without merging**
